-- ============================================================================
-- UkrEcoPelleta & ТОВ «УКРЕКОПЕЛЕТА» — Supabase Database Schema
-- Run this in your Supabase SQL Editor (100% Free Plan)
-- ============================================================================

-- 1. Create table for wholesale inquiries & leads
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    client_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT,
    city TEXT NOT NULL,
    volume TEXT,
    comment TEXT,
    
    -- Status pipeline
    status TEXT DEFAULT 'new' CHECK (status IN ('new', 'contacted', 'quote_sent', 'contract_signed', 'paid', 'delivered', 'cancelled')),
    estimated_tons NUMERIC,
    price_per_ton NUMERIC,
    total_amount NUMERIC,
    
    -- Ad Attribution & Analytics (Facebook, Instagram, Google Ads)
    utm_source TEXT,
    utm_medium TEXT,
    utm_campaign TEXT,
    utm_content TEXT,
    fbclid TEXT,
    gclid TEXT,
    ip_address TEXT,
    user_agent TEXT
);

-- 2. Create index for fast search by phone and city
CREATE INDEX IF NOT EXISTS idx_leads_phone ON public.leads(phone);
CREATE INDEX IF NOT EXISTS idx_leads_city ON public.leads(city);
CREATE INDEX IF NOT EXISTS idx_leads_created_at ON public.leads(created_at DESC);

-- 3. Row Level Security (RLS)
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

-- Allow anonymous form submissions from the website
CREATE POLICY "Allow public insert of leads"
ON public.leads
FOR INSERT
TO anon
WITH CHECK (true);

-- Only authenticated users (admins/sales team) can view or modify leads
CREATE POLICY "Allow authenticated staff to view all leads"
ON public.leads
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Allow authenticated staff to update leads"
ON public.leads
FOR UPDATE
TO authenticated
USING (true);

-- ============================================================================
-- 4. Alternative b2b_leads table (used by Vercel serverless api/lead.js)
--    If you use the Vercel backend, insert into this table instead of leads.
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.b2b_leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    name TEXT,
    phone TEXT NOT NULL,
    email TEXT,
    city TEXT,
    volume TEXT,
    comment TEXT,
    source TEXT DEFAULT 'web_form',
    status TEXT DEFAULT 'new'
        CHECK (status IN ('new','contacted','quote_sent','contract_signed','paid','delivered','cancelled')),
    -- Ad attribution
    utm_source TEXT,
    utm_medium TEXT,
    utm_campaign TEXT,
    utm_term TEXT,
    utm_content TEXT
);

CREATE INDEX IF NOT EXISTS idx_b2b_leads_phone ON public.b2b_leads(phone);
CREATE INDEX IF NOT EXISTS idx_b2b_leads_status ON public.b2b_leads(status);
CREATE INDEX IF NOT EXISTS idx_b2b_leads_created_at ON public.b2b_leads(created_at DESC);

ALTER TABLE public.b2b_leads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public insert of b2b leads"
ON public.b2b_leads FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow authenticated staff to view b2b leads"
ON public.b2b_leads FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated staff to update b2b leads"
ON public.b2b_leads FOR UPDATE TO authenticated USING (true);

-- ============================================================================
-- 5. Sample Query to inspect recent leads in Supabase:
-- SELECT id, name, phone, city, volume, utm_source, created_at
-- FROM public.b2b_leads
-- ORDER BY created_at DESC
-- LIMIT 20;
-- ============================================================================
